trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  APP_NAME: 'gym-hkdtbzfbg4fjeyad'  # Set your app name
  # Make sure FTP_PASSWORD is stored as a secret in Azure DevOps

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildAndDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: "18.x"
      displayName: "Install Node.js"

    # Install frontend dependencies and build
    - script: |
        npm install
        npm run build
      workingDirectory: ./FrontEnd
      displayName: "Install and build Frontend"

    # Copy built frontend (dist) to backend public directory
    - script: |
        mkdir -p ./BackEnd/public
        cp -r ./FrontEnd/dist/* ./BackEnd/public/
      displayName: "Copy Frontend build to Backend public directory"

    # Install backend dependencies
    - script: |
        npm install
      workingDirectory: ./BackEnd
      displayName: "Install Backend dependencies"

    # Create a ZIP archive of the Backend directory, including frontend build files, and exclude unnecessary files
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/BackEnd'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        verbose: true
        excludeFiles: '**/.zipignore'  # Exclude unnecessary files specified in .zipignore
      displayName: "Archive Backend and Frontend build into ZIP"

    # Deploy the ZIP file to Azure App Service via Kudu API
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          curl -X POST -u "$FTP_USERNAME:$FTP_PASSWORD" \
            -F "package=@$(Build.ArtifactStagingDirectory)/backend.zip" \
            https://$(APP_NAME).scm.azurewebsites.net/api/zipdeploy
      displayName: "Deploy ZIP to Azure App Service via Kudu"

    # Optional: Verify deployment and cleanup
    - script: |
        echo "Deployment completed successfully."
        # Add any additional verification or cleanup steps if needed
      displayName: "Verify and finalize deployment"
