trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Use Node.js version compatible with your project
- task: NodeTool@1
  inputs:
    versionSpec: '16.x' # Adjust the Node.js version if necessary
  displayName: 'Use Node.js'

# Checkout the repository (Optional: You can remove this if it's unnecessary)
- checkout: self
  displayName: 'Checkout repository code'

# Install NPM dependencies
- script: |
    npm install
  workingDirectory: ./ # Update if your package.json is in a subdirectory
  displayName: 'Install NPM dependencies'

# Run the unit test for TrainerProfile
- script: |
    npm test -- src/test/TrainerProfile.test.js --watchAll=false --reporters=default --reporters=jest-junit
  workingDirectory: ./ # Update if your package.json is in a subdirectory
  displayName: 'Run TrainerProfile unit test'

# Optional: If you want to collect code coverage reports
# - script: |
#     npm test -- --coverage --watchAll=false
#   workingDirectory: ./ # Update if your package.json is in a subdirectory
#   displayName: 'Run tests with code coverage'