trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

steps:
# Install Node.js version compatible with your project
- task: NodeTool@0
  inputs:
    versionSpec: "16.x"
  displayName: "Install Node.js"

# Install NPM dependencies and build the project using Vite
- script: |
    npm install
    npm run build
  workingDirectory: ./FrontEnd # Make sure the working directory is where package.json exists
  displayName: "npm install and build"

# Run the unit tests for TrainerProfile and append to JUnit report
- script: |
    npm test -- src/test/TrainerProfile.test.js --watchAll=false
  workingDirectory: ./FrontEnd # Path to package.json and tests
  displayName: 'Run TrainerProfile unit test'

# Run unit tests for ProgressLineGraph and append to JUnit report
- script: |
    npm test -- src/test/ProgressLineGraph.test.js --watchAll=false
  workingDirectory: ./FrontEnd # Path to package.json and tests
  displayName: 'Run ProgressLineGraph unit test'

# Run unit tests for navigation and append to JUnit report
- script: |
    npm test -- src/test/navigation.test.js --watchAll=false
  workingDirectory: ./FrontEnd # Path to package.json and tests
  displayName: 'Run Navigation unit test'

# Run unit tests for Sign Up page and append to JUnit report
- script: |
    npm test -- src/test/SignUp.test.js --watchAll=false
  workingDirectory: ./FrontEnd # Path to package.json and tests
  displayName: 'Run SignUp unit test'

# Publish the merged JUnit test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: './FrontEnd/test-reports/junit.xml' # Path to JUnit test result file
    testRunTitle: 'Merged Test Results'
    mergeTestResults: true

# Optional: If you want to collect code coverage reports
# - script: |
#     npm test -- --coverage --watchAll=false
#   workingDirectory: ./FrontEnd
#   displayName: 'Run tests with code coverage'