trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  APP_NAME: 'fitgymasd-ekcge9fqfebydsbr'  # Your Azure App Service exact name
  RESOURCE_GROUP: 'ASDFitGym_group'  # Your Azure resource group name

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
      # Install Node.js 18 to meet dependency requirements
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'  # Updated to Node.js 18
        displayName: 'Install Node.js 18.x'

      # Install backend dependencies
      - script: |
          cd BackEnd
          npm install
          npm install express
        displayName: 'Install Backend Dependencies'

      # Install frontend dependencies and run unit tests
      - script: |
          cd FrontEnd
          npm install
          npm test --watchAll=false  # Run unit tests without watch mode
        displayName: 'Run Frontend Unit Tests'

      # Publish the merged JUnit test results
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: './FrontEnd/junit.xml'  # Path to JUnit test result file, adjust if needed
          testRunTitle: 'Frontend Unit Test Results'
          mergeTestResults: true
        displayName: 'Publish Unit Test Results'

      # Build the frontend after tests pass
      - script: |
          cd FrontEnd
          npm run build
        displayName: 'Build Frontend'

      # Copy frontend build output to backend public directory
      - script: |
          mkdir -p BackEnd/public
          cp -r FrontEnd/dist/* BackEnd/public/
        displayName: 'Copy Frontend Build to Backend Public Directory'

      # Archive the entire backend (including frontend build files) for deployment
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/BackEnd'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        displayName: 'Archive Combined Backend and Frontend for Deployment'

      # Deploy to Azure App Service using Publish Profile via Curl and Kudu API
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo "Starting deployment using Publish Profile..."
            
            # Extract username and password from the publish profile
            PUBLISH_USERNAME=$(echo "$PUBLISH_PROFILE" | grep -oP '(?<=userName=")[^"]+')
            PUBLISH_PASSWORD=$(echo "$PUBLISH_PROFILE" | grep -oP '(?<=userPWD=")[^"]+')
            
            # Use the exact domain with region suffix for deployment
            curl -X POST -u "$PUBLISH_USERNAME:$PUBLISH_PASSWORD" \
                 -F "package=@$(Build.ArtifactStagingDirectory)/app.zip" \
                 https://fitgymasd-ekcge9fqfebydsbr.scm.australiacentral-01.azurewebsites.net/api/zipdeploy
            
            echo "Deployment to Azure App Service complete!"
        env:
          PUBLISH_PROFILE: $(PUBLISH_PROFILE)  # Explicitly map the secret as an environment variable
        displayName: 'Deploy to Azure App Service using Publish Profile and Curl'