trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  FTPS_URL: 'ftps://waws-prod-yt1-067.ftp.azurewebsites.windows.net/site/wwwroot'  # FTPS Endpoint
  FTP_USERNAME: 'gym\$gym'  # FTPS Username
  # Make sure FTP_PASSWORD is stored as a secret in Azure DevOps

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildAndDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: "18.x"
      displayName: "Install Node.js"

    # Install NPM dependencies and build
    - script: |
        npm install
        npm run build
      workingDirectory: ./FrontEnd
      displayName: "npm install and build"

    # Verify directory structure after build
    - script: |
        pwd
        ls -R ./FrontEnd
      displayName: "List Directory Structure After Build"

    # FTP Upload from ./FrontEnd/dist
    - task: FtpUpload@2
      inputs:
        credentialsOption: 'inputs'
        serverUrl: '$(FTPS_URL)'  # FTPS URL
        username: '$(FTP_USERNAME)'  # FTPS Username
        password: '$(FTP_PASSWORD)'  # Use secret variable from Azure DevOps
        rootDirectory: '$(System.DefaultWorkingDirectory)/FrontEnd/dist'  # Full path to dist folder
        filePatterns: '**/*'
        remoteDirectory: '/site/wwwroot'  # Target directory in App Service
        clean: true  # Clears out the target folder before uploading
        overwrite: true
      displayName: 'FTP Upload to Azure App Service'
