trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  FTPS_URL: 'ftps://gym-hkdtbzfbg4fjeyad.canadacentral-01.azurewebsites.net/site/wwwroot'  # Corrected FTPS Endpoint
  FTP_USERNAME: 'gym\$gym'  # FTPS Username
  # Make sure FTP_PASSWORD is stored as a secret in Azure DevOps

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildAndDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: "18.x"
      displayName: "Install Node.js"

    # Install frontend dependencies and build
    - script: |
        npm install
        npm run build
      workingDirectory: ./FrontEnd
      displayName: "Install and build Frontend"

    # Copy built frontend (dist) to backend public directory
    - script: |
        mkdir -p ./BackEnd/public
        cp -r ./FrontEnd/dist/* ./BackEnd/public/
      displayName: "Copy Frontend build to Backend public directory"

    # Install backend dependencies
    - script: |
        npm install
      workingDirectory: ./BackEnd
      displayName: "Install Backend dependencies"

    # Create a ZIP archive of the Backend directory, including frontend build files
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/BackEnd'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        verbose: true
      displayName: "Archive Backend and Frontend build into ZIP"

    # Verify ZIP file contents
    - script: |
        echo "Verifying ZIP contents:"
        unzip -l $(Build.ArtifactStagingDirectory)/backend.zip
      displayName: "Verify ZIP file contents"

    # Deploy the ZIP file to Azure App Service via Kudu API with retry logic
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          RETRIES=5
          while [ $RETRIES -gt 0 ]; do
            echo "Attempting deployment via Kudu API..."
            curl -X POST -u "$FTP_USERNAME:$FTP_PASSWORD" \
              -F "package=@$(Build.ArtifactStagingDirectory)/backend.zip" \
              https://gym-hkdtbzfbg4fjeyad.scm.azurewebsites.net/api/zipdeploy
            if [ $? -eq 0 ]; then
              echo "Deployment successful."
              break
            else
              echo "Deployment failed. Retrying in 10 seconds..."
              RETRIES=$((RETRIES - 1))
              sleep 10
            fi
          done
          if [ $RETRIES -eq 0 ]; then
            echo "Deployment failed after multiple attempts."
            exit 1
          fi
      displayName: "Deploy ZIP to Azure App Service via Kudu"
