trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_WEB_APP_NAME: 'gym'
  AZURE_WEB_APP_PACKAGE_PATH: '$(Build.ArtifactStagingDirectory)/backend.zip'
  FTP_USERNAME: 'gym\$gym'  # Use correct username format
  # Ensure FTP_PASSWORD is stored securely as a secret in Azure DevOps

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildAndDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: "18.x"
      displayName: "Install Node.js"

    # Install frontend dependencies and build
    - script: |
        npm install
        npm run build
      workingDirectory: ./FrontEnd
      displayName: "Install and build Frontend"

    # Copy built frontend (dist) to backend directory
    - script: |
        mkdir -p ./BackEnd/dist
        cp -r ./FrontEnd/dist/* ./BackEnd/dist/
      displayName: "Copy Frontend build to Backend dist directory"

    # Install backend dependencies
    - script: |
        npm install
      workingDirectory: ./BackEnd
      displayName: "Install Backend dependencies"

    # Create a ZIP file of the Backend directory (using .zipignore to skip large files)
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/BackEnd'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        verbose: true
        excludeFiles: '**/.zipignore'  # Use .zipignore to exclude unnecessary files
      displayName: "Create ZIP of Backend and Frontend build output"

    # Deploy the ZIP file to Azure App Service
    - task: AzureWebApp@1
      inputs:
        azureSubscription: '<Service Connection Name>'  # Replace with your actual Azure service connection name
        appType: 'webApp'
        appName: '$(AZURE_WEB_APP_NAME)'
        package: '$(AZURE_WEB_APP_PACKAGE_PATH)'
        deploymentMethod: 'zipDeploy'
      displayName: "Deploy ZIP to Azure App Service"
