trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

steps:
# Install Node.js version compatible with your project
- task: NodeTool@0
  inputs:
    versionSpec: "16.x"
  displayName: "Install Node.js"

# Install NPM dependencies and build the project
- script: |
    npm install
    npm run build
  workingDirectory: ./FrontEnd # Make sure the working directory is where package.json exists
  displayName: "npm install and build"
  
# Run the unit test for TrainerProfile
- script: |
    npm test -- src/test/TrainerProfile.test.js --watchAll=false --reporters=default --reporters=jest-junit
  workingDirectory: ./FrontEnd # Path to package.json and tests
  displayName: 'Run TrainerProfile unit test'

- script: |
    npm test -- src/test/ProgressLineGraph.test.js --watchAll=false --reporters=default --reporters=jest-junit
  workingDirectory: ./FrontEnd # Path to package.json and tests
  displayName: 'Run ProgressLineGraphByUser unit test'

# Optional: If you want to collect code coverage reports
# - script: |
#     npm test -- --coverage --watchAll=false
#   workingDirectory: ./FrontEnd # Ensure this is the correct path to your test files
#   displayName: 'Run tests with code coverage'