trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Use Node.js version compatible with your project
- task: NodeTool@0
  inputs:
    versionSpec: '16.x' # Adjust the Node.js version as per your project requirement
  displayName: 'Use Node.js'

# Checkout the repository
- task: Checkout@1
  displayName: 'Checkout repository code'

# Install NPM dependencies
- script: |
    ls -la # List directory content for debugging
    npm install
  workingDirectory: ./FrontEnd # Path to package.json
  displayName: 'Install NPM dependencies'

# Run the unit test for TrainerProfile
- script: |
    npm test -- src/test/TrainerProfile.test.js --watchAll=false --reporters=default --reporters=jest-junit
  workingDirectory: ./FrontEnd # Path to package.json and tests
  displayName: 'Run TrainerProfile unit test'

# Optional: If you want to collect code coverage reports
# - script: |
#     npm test -- --coverage --watchAll=false
#   workingDirectory: ./FrontEnd # Ensure this is the correct path to your test files
#   displayName: 'Run tests with code coverage'