trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

steps:
# Install Node.js version compatible with your project
- task: NodeTool@0
  inputs:
    versionSpec: "16.x"
  displayName: "Install Node.js"

# Install NPM dependencies and build the project using Vite
- script: |
    npm install
    npm run build
  workingDirectory: ./FrontEnd # Make sure the working directory is where package.json exists
  displayName: "npm install and build"

# Run the unit tests for TrainerProfile and append to JUnit report
- script: |
    npm test --watchAll=false
  workingDirectory: ./FrontEnd # Path to package.json and tests
  displayName: 'Run every unit test'

# Publish the merged JUnit test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: './FrontEnd/junit.xml' # Path to JUnit test result file, matches the output directory in package.json
    testRunTitle: 'Merged Test Results'
    mergeTestResults: true

# Optional: If you want to collect code coverage reports
# - script: |
#     npm test -- --coverage --watchAll=false
#   workingDirectory: ./FrontEnd
#   displayName: 'Run tests with code coverage'