trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  FTPS_URL: 'ftps://waws-prod-yt1-067.ftp.azurewebsites.windows.net/site/wwwroot'  # FTPS Endpoint
  FTP_USERNAME: 'gym\$gym'  # FTPS Username
  # Ensure FTP_PASSWORD is set in the Azure DevOps pipeline as a secret variable

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # Install Node.js version compatible with your project
    - task: NodeTool@0
      inputs:
        versionSpec: "18.x"
      displayName: "Install Node.js"

    # Install NPM dependencies and build the project using Vite
    - script: |
        npm install
        npm run build
      workingDirectory: ./FrontEnd # Ensure the path is correct for your setup
      displayName: "npm install and build"

- stage: Deploy
  displayName: 'Deploy the web application'
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - task: FtpUpload@2
      inputs:
        credentialsOption: 'inputs'
        serverUrl: '$(FTPS_URL)'  # FTPS URL
        username: '$(FTP_USERNAME)'  # FTPS Username
        password: '$(FTP_PASSWORD)'  # Use secret variable from Azure DevOps
        rootDirectory: './FrontEnd/dist'  # Directly from build output folder
        filePatterns: '**/*'
        remoteDirectory: '/site/wwwroot'  # Target directory in App Service
        clean: true  # Clears out the target folder before uploading
        overwrite: true
      displayName: 'FTP Upload to Azure App Service'
