trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Use Node.js version compatible with your project
- task: NodeTool@1
  inputs:
    versionSpec: '16.x'
  displayName: 'Use Node.js'

# Checkout the repository
- task: Checkout@1
  displayName: 'Checkout repository code'

# Install NPM dependencies inside FrontEnd directory
- script: |
    npm install
  workingDirectory: ./FrontEnd  # Correct path to the directory where package.json is located
  displayName: 'Install NPM dependencies'

# Run the unit test for TrainerProfile
- script: |
    npm test -- src/test/TrainerProfile.test.js --watchAll=false --reporters=default --reporters=jest-junit
  workingDirectory: ./FrontEnd  # Correct path to the directory where package.json is located
  displayName: 'Run TrainerProfile unit test'